# Generated by Django 2.2 on 2022-03-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_notes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
