# Generated by Django 2.2 on 2022-03-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220304_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='date',
        ),
        migrations.AlterField(
            model_name='notes',
            name='img',
            field=models.ImageField(upload_to='image'),
        ),
    ]
